#################
### AUTOSTART ###
#################

exec-once = waybar
exec-once = copyq &
exec-once = swww-daemon
exec-once = iwctl station wlan0 scan
exec-once = hyprland-per-window-layout
exec-once = gsettings set org.gnome.desktop.interface color-scheme "prefer-dark"
