###############
### PLUGINS ###
###############

exec-once = hyprpm reload -n

plugin {
  hyprexpo {
    columns = 3
    gap_size = 0
  }
  dynamic-cursors {
    mode = rotate
    rotate {
      offset = 20
    }
  }
}

bind = SUPER, W, hyprexpo:expo, toggle
