################
### PROGRAMS ###
################

$terminal = kitty
$clipboard = copyq toggle
$file_manager = $terminal -e yazi


################
### KEYBINDS ###
################

# Screenshots
$screenshot = flameshot gui -c
$fullscreen_screenshot = flameshot screen -c

# Switches
$bar_switch = pgrep waybar && pkill -SIGUSR1 waybar || waybar &
$app_launcher_switch = killall wofi || $(hyprctl keyword input:kb_layout us; wofi --show drun; hyprctl keyword input:kb_layout us, ru)
$window_selector_switch = killall rofi || $(hyprctl keyword input:kb_layout us; rofi -show window; hyprctl keyword input:kb_layout us, ru)

