####################
### CUSTOM RULES ###
####################

windowrule {
  name = terraria-debug
  match:class = dotnet

  float = true
  center = true
  size = 80% 80%
}

windowrule {
  name = pavucontrol
  match:class = org.pulseaudio.pavucontrol

  float = true
  move = 1170 24
  size = 748 800
}

windowrule {
  name = copyq
  match:class = com.github.hluk.copyq

  float = true
  center = true
  size = 800 400
}

windowrule {
  name = iwctl
  match:class = iwctl

  float = true
  center = true
  size = 800 400
}


###########
### PIP ###
###########

windowrule {
  name = browser-pip
  match:class = zen
  match:title = Picture-in-Picture

  float = true
  size = 800 450
  pin = true
}

windowrule {
  name = discord-popout
  match:title = Discord Popout

  float = true
  move = 100%-800 0
  size = 800 450
  pin = true
}

windowrule {
  name = spotify-popout
  match:title = Picture in picture
  match:xwayland = 0

  float = true
  move = 1572 126
  size = 328 328
}


#####################
### DEFAULT RULES ###
#####################

# No gaps when only one window
workspace = w[tv1], gapsout:0, gapsin:0
workspace = f[1], gapsout:0, gapsin:0
windowrule {
  name = no_gaps-wtv1
  match:float = false
  match:workspace = w[tv1]

  border_size = 0
  rounding = 0
}

windowrule {
  name = no_gaps-f1
  match:float = false
  match:workspace = f[1]

  border_size = 0
  rounding = 0
}

# Ignore maximize requests from apps.
windowrule {
  name = suppress-maximize-events
  match:class = .*

  suppress_event = maximize
}

# Fix some dragging issues with XWayland
windowrule {
  name = fix-xwayland-drags
  match:class = ^$
  match:title = ^$
  match:xwayland = true
  match:float = true
  match:fullscreen = false
  match:pin = false

  no_focus = true
}
