####################
### CUSTOM RULES ###
####################

# Pseudo special WS
windowrule = pseudo, onworkspace: s[1]

# Terraria debug
windowrule = float, initialClass: ^(?i)(terraria)(.*)

# Pavucontrol
windowrule = float, move 1010 24, size 901 400, initialClass: org.pulseaudio.pavucontrol


###########
### PIP ###
###########

# Browser pip
$browser_pip = class: zen, title: Picture-in-Picture
windowrule = float, size 800 450, $browser_pip

# Discord popout
$discord_popout = initialTitle: Discord Popout
windowrule = float, size 800 450, move 100%-800 0, $discord_popout

# Spotify lyrics popup
$spotify_popup = title: Picture in picture, initialTitle: Picture in picture, xwayland: 0
windowrule = float, size 328 328, move 1572 126, $spotify_popup


#####################
### DEFAULT RULES ###
#####################

# No gaps when only one window
workspace = f[1]s[0], gapsout:0, gapsin:0
workspace = w[tv1]s[0], gapsout:0, gapsin:0
windowrule = bordersize 0, rounding 0, floating: 0, onworkspace: f[1]s[0]
windowrule = bordersize 0, rounding 0, floating: 0, onworkspace: w[tv1]s[0]

# Ignore maximize requests from apps.
windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus, class: ^$, title: ^$, xwayland: 1, floating: 1, fullscreen: 0, pinned: 0
