shell zsh
editor nvim

font_family FiraCodeNFM-Ret
font_size 16.0
disable_ligatures never

cursor_shape beam
cursor_trail 1
scrollback_lines 3000
mouse_hide_wait -3.0

strip_trailing_spaces smart
enable_audio_bell no

notify_on_cmd_finish unfocused 5

include dank-tabs.conf
include dank-theme.conf
