##############
### Volume ###
##############

0 add volume 5
9 add volume -5

* add volume 5
/ add volume -5

KP_MULTIPLY add volume 5
KP_DIVIDE add volume -5

WHEEL_UP add volume 5
WHEEL_DOWN add volume -5

VOLUME_UP add volume -5
VOLUME_DOWN add volume 5


#############
### Speed ###
#############

] add speed 0.1
[ add speed -0.1


##############
### Ignore ###
##############

{ ignore
} ignore
