################
### PROGRAMS ###
################

$menu = wofi
$bar = waybar
$terminal = kitty
$filemanager = $terminal -e yazi


#########################
### COMMANDS/KEYBINDS ###
#########################

# Screenshots
$screenshot = flameshot gui -c
$fullscreen_screenshot = flameshot screen -c

# Switches
$menu_switch = killall $menu || $menu
$bar_switch = pgrep $bar && pkill -SIGUSR1 $bar || $bar &


#############
### PATHS ###
#############

$hyprland_config_home = ~/.config/hypr/land
