####################
### TILING RULES ###
####################

windowrule = pseudo, onworkspace: s[1]

# Terraria debug
windowrule = float, initialClass: ^(?i)(terraria)(.*)

# No gaps when only one window
workspace = f[1]s[0], gapsout:0, gapsin:0
workspace = w[tv1]s[0], gapsout:0, gapsin:0
windowrule = bordersize 0, rounding 0, floating: 0, onworkspace: f[1]s[0]
windowrule = bordersize 0, rounding 0, floating: 0, onworkspace: w[tv1]s[0]

# Spotify lyrics popup
$spotify_popup = xwayland: 1, initialTitle: Picture in picture
windowrule = move 1572 126, size 328 328, $spotify_popup

# Picture-in-picture
$pip_title = initialTitle: ^(?i)(discord(.*)popout|picture(.*)in(.*)picture)$
windowrule = float, size 800 450, $pip_title

# Pavucontrol
windowrule = float, move 1010 24, size 901 400, initialClass: org.pulseaudio.pavucontrol

# Ignore maximize requests from apps.
#windowrule = suppressevent maximize, class:.*

# Fix some dragging issues with XWayland
windowrule = nofocus, class: ^$, title: ^$, xwayland: 1, floating: 1, fullscreen: 0, pinned: 0
