####################
### HYPR CONFIGS ###
####################

source = ~/.config/hypr/land/vars.conf
source = $hyprland_config_home/env.conf
source = $hyprland_config_home/windows.conf
source = $hyprland_config_home/plugins.conf
source = $hyprland_config_home/monitors.conf
source = $hyprland_config_home/keybinds.conf
source = $hyprland_config_home/autostart.conf


#############
### INPUT ###
#############

# https://wiki.hypr.land/Configuring/Variables/#input
input {
  kb_layout = us, ru
  kb_options = grp:win_space_toggle

  follow_mouse = 1
  sensitivity = -0.4
}

#####################
### LOOK AND FEEL ###
#####################

# https://wiki.hypr.land/Configuring/Variables/

# https://wiki.hypr.land/Configuring/Variables/#general
general {
  border_size = 2
  resize_on_border = true
  gaps_in = 1
  gaps_out = 2

  # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
  col.active_border =   rgba(b14242aa)
  col.inactive_border = rgba(00000000)

  # https://wiki.hypr.land/Configuring/Tearing/
  allow_tearing = false

  layout = dwindle
}

# https://wiki.hypr.land/Configuring/Variables/#decoration
decoration {
  rounding = 4
  rounding_power = 2

  blur:enabled = false
  shadow:enabled = false
}

# https://wiki.hypr.land/Configuring/Variables/#animations
animations:enabled = false

# https://wiki.hypr.land/Configuring/Variables/#misc
misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  initial_workspace_tracking = 1
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle:preserve_split = true

# https://wiki.hypr.land/Configuring/Master-Layout/
master:new_status = master


###################
### PERMISSIONS ###
###################

# https://wiki.hypr.land/Configuring/Permissions/
# Permission changes require a Hyprland restart

ecosystem:no_update_news = true
