background {
  monitor =
  path = $HOME/Wallpapers/Kikuri_wallpaper.jpg
  color = rgba(44, 37, 37, 1.0)
  blur_passes = 1
  blur_size = 3
}

lable {
  monitor = 
  text = cmd[update:1000] echo $TIME
}

input-field {
  monitor =
  size = 350, 60
  dots_size = 0.8
  dots_spacing = -0.25 
  dots_center = true
  dots_text_format = ~~
  placeholder_text = 
  fail_text = nope 
  fade_on_empty = true 
  fade_timeout = 500
  outer_color = rgba(0, 0, 0, 0)
  inner_color = rgba(0, 0, 0, 0.2)
  font_color = rgba(0, 255, 205, 1)
  font_family = Fira Code
  check_color = rgb(204, 136, 34)
  position = 0, -250
  halgin = center
  valgin = center
}

