####################
### HYPR CONFIGS ###
####################

$hyprland_config_home = ~/.config/hypr/land

source = $hyprland_config_home/vars.conf
source = $hyprland_config_home/env.conf
source = $hyprland_config_home/windows.conf
source = $hyprland_config_home/plugins.conf
source = $hyprland_config_home/monitors.conf
source = $hyprland_config_home/keybinds.conf
source = $hyprland_config_home/autostart.conf


#############
### INPUT ###
#############

input {
  kb_layout = us, ru
  kb_options = grp:win_space_toggle

  follow_mouse = 1
  sensitivity = 0.5
  gesture = 3, horizontal, workspace
  gesture = 3, up, fullscreen
}

#####################
### LOOK AND FEEL ###
#####################

general {
  border_size = 2
  gaps_in = 0
  gaps_out = 0

  col.active_border =   rgba(b14242aa)
  col.inactive_border = rgba(00000000)

  allow_tearing = false

  layout = dwindle
}

decoration {
  rounding = 0
  rounding_power = 0

  blur:enabled = false
  shadow:enabled = false
}

animations:enabled = false

misc {
  force_default_wallpaper = 0
  disable_hyprland_logo = true
  initial_workspace_tracking = 1
}

dwindle:preserve_split = true

master:new_status = master


#############
### OTHER ###
#############

ecosystem:no_update_news = true

debug {
  disable_logs = false
  enable_stdout_logs = 1
  error_position = 1
}
