[mgr]
show_hidden = true

[preview]
wrap = "yes"
tab_size = 2
max_width  = 1920
max_height = 1080

[opener]
edit = [
  { run = "nvim -O %s", desc = "Edit", block = true },
  { run = "nvim -d %s", desc = "Diff", block = true },
]

wine = [
  { run = "wine %s", desc = "Wine", orphan = true },
]

java = [
  { run = "java -jar %s", desc = "Launch jar", orphan = true },
]

[open]
prepend_rules = [
  { url = "*.exe",  use = "wine" },
  { url = "*.jar",  use = "java" },
]
