[mgr]
show_hidden = true

[preview]
wrap = "yes"
tab_size = 2

[opener]
edit = [
  { run = 'nvim -O"$n" "$@"', desc = "Edit", block = true }
]

open = [
  { run = 'xdg-terminal-exec', desc = "Open", orphan = true }
]

script = [
  { run = 'xdg-terminal-exec bash "$@"', desc = "Bash", orphan = true }
]

wine = [
  { run = 'xdg-terminal-exec wine "$@"', desc = "Wine", orphan = true }
]

java = [
  { run = 'xdg-terminal-exec java -jar "$@"', desc = "Launch jar", orphan = true }
]

term = [
]

[open]
prepend_rules = [
  { url = "*.sh",              use = [ "edit", "script" ] },
  { mime = "text/shellscript", use = [ "edit", "script" ] },

  { url = "*.exe",  use = "wine" },
  { url = "*.jar",  use = "java" },
]

append_rules = [
  { mime = "*", use = "open" },
]
