[mgr]
show_hidden = true

[preview]
wrap = "yes"
tab_size = 2
max_width  = 1920
max_height = 1080

[opener]
edit = [
  { run = 'nvim -O"$n" "$@"', desc = "Edit", block = true },
  { run = 'nvim -d "$@"',     desc = "Diff", block = true },
]

script = [
  { run = 'bash "$@"', desc = "Bash", orphan = true },
]

wine = [
  { run = 'wine "$@"', desc = "Wine", orphan = true },
]

java = [
  { run = 'java -jar "$@"', desc = "Launch jar", orphan = true },
]

[open]
prepend_rules = [
  { url = "*.sh",              use = [ "edit", "script" ] },
  { mime = "text/shellscript", use = [ "edit", "script" ] },

  { url = "*.exe",  use = "wine" },
  { url = "*.jar",  use = "java" },
]
